<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>fbs</string>
    </array>
    <key>name</key>
    <string>Flatbuffers Schema</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#value</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespace-decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attribute-decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#include-decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#enum-decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#union-decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#struct-decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#table-decl</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#root_type-decl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(attribute|include|file_identifier|file_extension)\b</string>
        <key>name</key>
        <string>keyword.control.flatbuffers</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>line-comment</key>
      <dict>
        <key>begin</key>
        <string>(?=//)</string>
        <key>end</key>
        <string>\n</string>
        <key>name</key>
        <string>comment.line.double-slash.flatbuffers</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(?&lt;!/)(?=///[^/])</string>
            <key>end</key>
            <string>(?=\n)</string>
            <key>name</key>
            <string>meta.documentation.flatbuffers</string>
          </dict>
        </array>
      </dict>
      <key>block-comment</key>
      <dict>
        <key>begin</key>
        <string>(?=/\*)</string>
        <key>end</key>
        <string>(?&lt;!/)\*/</string>
        <key>name</key>
        <string>comment.block.flatbuffers</string>
      </dict>
      <key>escape-chars</key>
      <dict>
        <key>match</key>
        <string>\\(?:['"\?\\abfnrtv]|[0-7]{1,3}|x[\da-fA-F]+|u[\da-fA-F]{4}|U[\da-fA-F]{8})</string>
        <key>name</key>
        <string>constant.character.escape.flatbuffers</string>
      </dict>
      <key>invalid-escape-chars</key>
      <dict>
        <key>match</key>
        <string>\\(?:[^'"\?\\abfnrtvxuU0-7]|x[^\da-fA-F]|u[\da-fA-F]{0,3}[^\da-fA-F]|U[\da-fA-F]{0,7}[^\da-fA-F])</string>
        <key>name</key>
        <string>invalid.illegal.unknown-escape.flatbuffers</string>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.flatbuffers</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.flatbuffers</string>
          </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.flatbuffers</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#escape-chars</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid-escape-chars</string>
          </dict>
        </array>
      </dict>
      <key>scalar</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
            <key>name</key>
            <string>constant.language.flatbuffers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
        </array>
      </dict>
      <key>object</key>
      <dict>
        <key>begin</key>
        <string>{</string>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#name</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>:</string>
            <key>end</key>
            <string>,|}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#value</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#name</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>typename</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\.)?\s*\b(bool|byte|ubyte|short|ushort|int|uint|float|long|ulong|double|int8|uint8|int16|uint16|int32|uint32|int64|uint64|float32|float64|string)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.flatbuffers</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>storage.type.flatbuffers</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?!(enum|namespace|union|struct|table|include|true|false|null|bool|byte|ubyte|short|ushort|int|uint|float|long|ulong|double|int8|uint8|int16|uint16|int32|uint32|int64|uint64|float32|float64|string)\W)([_a-zA-Z]\w*)\s*(?=\.)</string>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.section.flatbuffers</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?!(enum|namespace|union|struct|table|include|true|false|null|bool|byte|ubyte|short|ushort|int|uint|float|long|ulong|double|int8|uint8|int16|uint16|int32|uint32|int64|uint64|float32|float64|string)\W)([_a-zA-Z]\w*)</string>
            <key>name</key>
            <string>entity.name.type.flatbuffers</string>
          </dict>
        </array>
      </dict>
      <key>name</key>
      <dict>
        <key>match</key>
        <string>\b(?!(enum|namespace|union|struct|table|include|true|false|null|bool|byte|ubyte|short|ushort|int|uint|float|long|ulong|double|int8|uint8|int16|uint16|int32|uint32|int64|uint64|float32|float64|string)\W)([_a-zA-Z]\w*)\b</string>
        <key>name</key>
        <string>entity.name.tag.flatbuffers</string>
      </dict>
      <key>packname</key>
      <dict>
        <key>match</key>
        <string>\b(?!(enum|namespace|union|struct|table|include|true|false|null|bool|byte|ubyte|short|ushort|int|uint|float|long|ulong|double|int8|uint8|int16|uint16|int32|uint32|int64|uint64|float32|float64|string)\W)([_a-zA-Z]\w*)\b</string>
        <key>name</key>
        <string>entity.name.section.flatbuffers</string>
      </dict>
      <key>numeric</key>
      <dict>
        <key>match</key>
        <string>(-)?\d+(\.\d+)?</string>
        <key>name</key>
        <string>constant.numeric.flatbuffers</string>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#line-comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-comment</string>
          </dict>
        </array>
      </dict>
      <key>value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#scalar</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
        </array>
      </dict>
      <key>struct_field_end</key>
      <dict>
        <key>begin</key>
        <string>\b\s*(:)</string>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typename</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[\d=]+</string>
            <key>name</key>
            <string>invalid.illegal.flatbuffers</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>invalid.illegal.flatbuffers</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(\\\\)|\\"</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#metadata</string>
          </dict>
        </array>
      </dict>
      <key>table_field_end</key>
      <dict>
        <key>begin</key>
        <string>\b\s*(:)</string>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typename</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>=</string>
            <key>end</key>
            <string>(?=;|\()</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#value</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#name</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#metadata</string>
          </dict>
        </array>
      </dict>
      <key>metadata</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(id|deprecated|required|original_order|force_align|bit_flags|nested_flatbuffer|key|csharp_partial)\b</string>
            <key>name</key>
            <string>keyword.control.flatbuffers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#scalar</string>
          </dict>
        </array>
      </dict>
      <key>namespace-decl</key>
      <dict>
        <key>begin</key>
        <string>\b(namespace)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.flatbuffers</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#packname</string>
          </dict>
        </array>
      </dict>
      <key>enum-decl</key>
      <dict>
        <key>begin</key>
        <string>\b(enum)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.flatbuffers</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typename</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#metadata</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>{</string>
            <key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#name</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#numeric</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>union-decl</key>
      <dict>
        <key>begin</key>
        <string>\b(union)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.flatbuffers</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typename</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#metadata</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>{</string>
            <key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#typename</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>struct-decl</key>
      <dict>
        <key>begin</key>
        <string>\b(struct)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.flatbuffers</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typename</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#metadata</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>{</string>
            <key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#name</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#struct_field_end</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>table-decl</key>
      <dict>
        <key>begin</key>
        <string>\b(table)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.flatbuffers</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;=})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typename</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#metadata</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>{</string>
            <key>end</key>
            <string>}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#name</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#table_field_end</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>root_type-decl</key>
      <dict>
        <key>begin</key>
        <string>\b(root_type)\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.flatbuffers</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#typename</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.flatbuffers</string>
  </dict>
</plist>